# MySQL 配置
[mysql]
host = localhost
port = 3306
user = root
password = 123456
database = rag_item

# Redis 配置
[redis]
host = localhost
port = 6379
password = 1234
db = 1

# 日志配置
[logger]
# 建议绝对路径，因为相对路径容易出错。在实际生产环境，打到docker。在docker内部 根目录下/var/logs , /opt/logs
log_file = integrated_qa_system/logs/app.log

# Milvus 配置
[milvus]
host = 127.0.0.1
port = 19530
database_name = medical
collection_name = c1

# LLM 配置
[llm]
model = deepseek-v3.2
dashscope_api_key = sk-cc93a0763c004b9c92a842cbd453a1c1
dashscope_base_url = https://dashscope.aliyuncs.com/compatible-mode/v1

# 检索参数配置
[retrieval]
parent_chunk_size = 1200
child_chunk_size = 300
chunk_overlap = 50
# milvus混合检索使用
retrieval_k = 10
# rerank以后的结果
candidate_m = 3

# 应用配置
[app]
valid_sources = ["ai", "java", "test", "ops", "bigdata"]
customer_service_phone = 12345678
